permalink: /:categories/:year-:month-:day/:title
url : https://exploit.moe
author :
  name : Hayato Doi
  screen_name : ノノノノ
  twitter : no_______nonono
excerpt : This is ノノノノ's web site.
title : EXPLOIT.MOE
domain :
  upper : EXPLOIT.MOE
  lower : exploit.moe
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: ./assets/css
