version: '3.7'
services:
  jekyll:
    image: jekyll/jekyll:pages
    environment:
      JEKYLL_ENV: docker
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    command: >
      jekyll serve \
        --watch \
        --force_polling \
        --config  _config.yml,_config.docker.yml